"""Recommendation Service — Component 7 (Updated Orchestrator).

Integrates all components:
  - Data parser (_build_scene_rows) — kept from original, enhanced with confidence fields
  - Genre classifier (new data-driven version)
  - Trailer baseline builder (new)
  - Structure analyzer (new energy-based version)
  - Problem detector / recommendation engine (new evidence-based version)
  - Scene ratio analyzer (new confidence-weighted version)

Maintains full backward compatibility with RecommendationResponse schema.
"""
from __future__ import annotations

import logging
import re
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from app.core.config import get_settings
from app.schemas.recommendation_schema import (
    Evidence,
    GenreReport,
    PopularityContext,
    Recommendation,
    RecommendationRequest,
    RecommendationResponse,
    RecommendationSummary,
    SentimentContext,
    TrailerProfile,
)
from app.services.trailer_type_detector import detect_trailer_type, get_act_phase
from app.services.genre_classifier import ALL_GENRES, build_genre_report
from app.services.scene_type_genre import genre_from_scene_types
# OMDb is still needed — not for genre any more, but to know the film's REAL
# title and release date, which the on-screen text checks compare OCR against.
from app.services.movie_metadata_fetcher import fetch_movie_metadata
from app.services.structure_segmentation import infer_beats
from app.services.scene_ratio_analyzer import analyze_ratios
from app.services.trailer_baseline import build_trailer_baseline
from app.services.cinematic_recommendation_engine import generate_cinematic_recommendations

MODEL_NAME = "EditorialProblemClassifier"
MODEL_VERSION_DEFAULT = "v4.0-ProblemClassification"

logger = logging.getLogger(__name__)


def _load_model_metrics() -> dict[str, Any]:
    """Measured performance of the model that actually produces findings.

    This used to report metrics for recommendation_model.joblib, which was
    trained on labels generated by the same heuristic it replaced and was
    never loaded at runtime. It now reports the editorial-problem classifier,
    read from the trained bundle itself so the numbers cannot drift away from
    the model in use.
    """
    from app.services.problem_model import PROBLEM_CLASSES, load_model

    bundle = load_model()
    if bundle is None:
        return {
            "model": "editorial-problem-classifier",
            "status": "not trained — run scripts/train_problem_model.py",
        }
    return {
        "model": "editorial-problem-classifier (RandomForest)",
        "cv_accuracy": bundle.get("cv_accuracy"),
        "cv_strategy": bundle.get("cv_strategy", "legacy window-level split"),
        "trained_on_trailers": bundle.get("trained_on"),
        "training_examples": bundle.get("n_examples"),
        "problem_classes": list(PROBLEM_CLASSES),
        "training_data_source": (
            "professional trailers with deliberate, named editorial defects applied "
            "— labels come from the applied defect, not from a heuristic's own output"
        ),
    }




def _number(value: Any, default: float = 0.0) -> float:
    try:
        number = float(value)
        return number if np.isfinite(number) else default
    except (TypeError, ValueError):
        return default


def _score(value: Any) -> float:
    number = _number(value)
    return max(0.0, min(1.0, number / 100 if number > 1 else number))


def _text(value: Any, default: str = "unknown") -> str:
    if value is None:
        return default
    text = str(value).strip()
    return text or default


def _pick(row: dict[str, Any], *keys: str, default: Any = None) -> Any:
    for key in keys:
        if key in row and row[key] is not None:
            return row[key]
    return default


def _parse_shot_duration(timeframe: str) -> float:
    try:
        start_text, end_text = timeframe.split("-")
        def _to_seconds(text: str) -> float:
            parts = [float(p) for p in text.strip().split(":")]
            sec = 0.0
            for p in parts:
                sec = sec * 60 + p
            return sec
        return max(1.0, _to_seconds(end_text) - _to_seconds(start_text))
    except Exception:
        return 8.0


def _build_scene_rows(payload: RecommendationRequest) -> list[dict[str, Any]]:
    """Builds clean, normalized scene feature rows from multimodal backend outputs.

    Enhanced to include scene_type_confidence and classification_reliable fields.
    """
    final_rows = payload.final_system_output or []
    audio_rows = payload.audio_feature_output or []
    visual_rows = payload.visual_feature_output or []
    scene_count = max(len(final_rows), len(audio_rows), len(visual_rows))
    rows: list[dict[str, Any]] = []

    total_duration = 0.0
    for idx in range(scene_count):
        final = final_rows[idx] if idx < len(final_rows) else {}
        timeframe = _text(_pick(final, "time", "timestamp", default=f"00:{idx*8:02d}-00:{(idx+1)*8:02d}"))
        total_duration += _parse_shot_duration(timeframe)

    trailer_type = detect_trailer_type(total_duration, scene_count)

    for index in range(scene_count):
        final = final_rows[index] if index < len(final_rows) else {}
        audio = audio_rows[index] if index < len(audio_rows) else {}
        visual = visual_rows[index] if index < len(visual_rows) else {}

        scene = int(_number(_pick(final, "scene", "scene_id", default=index + 1), index + 1))
        timeframe = _text(_pick(final, "time", "timestamp", default=_pick(visual, "time", "timestamp", default=f"00:{index*8:02d}-00:{(index+1)*8:02d}")))
        position_ratio = (index + 0.5) / max(scene_count, 1)

        act = get_act_phase(position_ratio, trailer_type)

        face_emo = _text(_pick(final, "face_emotion", "visual_emotion", "emotion", default=_pick(visual, "face_emotion", "visual_emotion", "emotion", default="neutral")))
        if face_emo in ["left", "right"]:
            face_emo = _text(_pick(final, "video_emotion", "visual_emotion", default="neutral"))
            if face_emo in ["left", "right"]:
                face_emo = "neutral"

        # Extract scene_type_confidence and classification_reliable
        scene_type_conf = _number(
            _pick(final, "scene_type_confidence", "fusion_confidence",
                  default=_pick(visual, "scene_type_confidence", default=1.0)),
            1.0
        )
        classification_reliable_raw = _pick(
            final, "classification_reliable",
            default=_pick(visual, "classification_reliable", default=True)
        )
        classification_reliable = bool(classification_reliable_raw) if classification_reliable_raw is not None else True

        evidence = Evidence(
            ei=_score(_pick(final, "ei", "EI", "emotional_intensity", "intensity_score")),
            audio_energy=_score(_pick(final, "audio_energy", "A", "audioEnergy", default=_pick(audio, "audioEnergy", "audio_energy", "A"))),
            motion=_score(_pick(final, "motion", "M", "motion_intensity", default=_pick(visual, "motion", "motion_intensity", "M"))),
            object_score=_score(_pick(final, "object_score", "O", "objectScore", default=_pick(visual, "objectScore", "object_score", "O"))),
            emotion_confidence=_score(_pick(final, "emotion_confidence", "F", default=_pick(visual, "emotionConfidence", "emotion_confidence", "F", default=0.85))),
            scene_type=_text(_pick(final, "scene_type", "sceneType", default=_pick(visual, "scene_type", "sceneType", default="Drama"))),
            scene_type_confidence=scene_type_conf,
            classification_reliable=classification_reliable,
            visual_emotion=face_emo,
            audio_mood=_text(_pick(final, "audio_mood", "mood", default=_pick(audio, "audioMood", "audio_mood", "mood", default="emotional"))),
            act=act,
            audio_emotion=_text(_pick(final, "audio_emotion", default=_pick(audio, "audio_emotion", default="neutral"))),
            tempo_bpm=_number(_pick(final, "tempo_bpm", default=_pick(audio, "tempo_bpm", default=120.0)), 120.0),
            mfcc_mean=_number(_pick(final, "mfcc_mean", default=_pick(audio, "mfcc_mean", default=0.0)), 0.0),
            spectral_centroid=_number(_pick(final, "spectral_centroid", default=_pick(audio, "spectral_centroid", default=1800.0)), 1800.0),
            shot_duration=_parse_shot_duration(timeframe),
            objects=_text(_pick(final, "objects", default=_pick(visual, "objects", default="person")), "person"),
        )

        rows.append({
            "scene": scene,
            "timeframe": timeframe,
            "evidence": evidence,
            "act": act,
            "position_pct": position_ratio
        })

    return rows


def _refine_scene_types(scene_rows: list[dict[str, Any]]) -> dict[str, int]:
    """Correct only isolated, low-confidence scene labels.

    Trailer cuts legitimately change scene type quickly, so broad temporal
    smoothing would erase real transitions. A label is changed only when both
    immediate neighbours are reliable, agree, and the current prediction is
    uncertain. Unresolved very-low-confidence labels are marked unreliable so
    later genre and intent logic cannot treat them as facts.
    """
    if not scene_rows:
        return {"corrected": 0, "unreliable": 0}

    original = [row["evidence"].scene_type for row in scene_rows]
    confidences = [
        max(0.0, min(1.0, float(row["evidence"].scene_type_confidence or 0.0)))
        for row in scene_rows
    ]
    reliable = [
        bool(row["evidence"].classification_reliable) and confidence >= 0.45
        for row, confidence in zip(scene_rows, confidences)
    ]

    corrected = 0
    for index in range(1, len(scene_rows) - 1):
        evidence = scene_rows[index]["evidence"]
        if confidences[index] >= 0.55 and reliable[index]:
            continue

        neighbour_type = original[index - 1]
        neighbours_agree = (
            reliable[index - 1]
            and reliable[index + 1]
            and neighbour_type == original[index + 1]
            and neighbour_type != original[index]
        )
        if not neighbours_agree:
            continue

        evidence.scene_type = neighbour_type
        evidence.scene_type_confidence = round(
            min(0.78, (confidences[index - 1] + confidences[index + 1]) * 0.425),
            4,
        )
        evidence.classification_reliable = True
        scene_rows[index]["scene_type_refinement"] = {
            "original": original[index],
            "refined": neighbour_type,
            "reason": "matching reliable adjacent scenes",
        }
        corrected += 1

    unreliable = 0
    for row in scene_rows:
        evidence = row["evidence"]
        evidence.scene_type_confidence = max(
            0.0, min(1.0, float(evidence.scene_type_confidence or 0.0))
        )
        if evidence.scene_type_confidence < 0.35:
            evidence.classification_reliable = False
            unreliable += 1

    return {"corrected": corrected, "unreliable": unreliable}


# ==============================================================================
# STEP 2: SCENE SIGNAL WEAKNESS CALCULATION
# Evaluates 5 multimodal signals per scene to find the weakest dimension
# and calculates a weakness-based priority score (10 to 100).
# ==============================================================================
def _normalise_genre_mixture(value: Any) -> dict[str, float]:
    if not isinstance(value, dict):
        return {}
    supported = {genre.lower(): genre for genre in ALL_GENRES}
    mixture: dict[str, float] = {}
    for raw_genre, raw_score in value.items():
        canonical = supported.get(str(raw_genre).strip().lower())
        score = _number(raw_score)
        if canonical and score > 0:
            mixture[canonical] = mixture.get(canonical, 0.0) + score
    total = sum(mixture.values())
    if total <= 0:
        return {}
    return {genre: score / total for genre, score in mixture.items()}


def _classify_genre(
    scene_rows: list[dict[str, Any]],
    trailer_title: str,
    total_duration_sec: float,
    insights: dict[str, Any] | None = None,
    metadata: dict[str, Any] | None = None,
):
    """Decide the trailer's genre from its own scenes using multimodal feature aggregation.

    Aggregates scene-type distribution, audio mood, facial valence/arousal,
    and motion/energy profiles into a probabilistic genre report.
    """
    multimodal_report = build_genre_report(scene_rows, trailer_title)

    insights = insights if isinstance(insights, dict) else {}
    upstream_mixture = _normalise_genre_mixture(insights.get("genre_mixture"))
    supported = {genre.lower(): genre for genre in ALL_GENRES}
    upstream_primary = supported.get(
        str(insights.get("dominant_genre") or "").strip().lower()
    )
    upstream_secondary = supported.get(
        str(insights.get("secondary_genre") or "").strip().lower()
    )

    metadata_genres: list[str] = []
    if isinstance(metadata, dict):
        for genre in metadata.get("genres") or []:
            canonical = supported.get(str(genre).strip().lower())
            if canonical and canonical not in metadata_genres:
                metadata_genres.append(canonical)

    if upstream_primary:
        # Blend the complete-trailer analysis with this service's local view,
        # but use the explicit upstream result to break near-uniform ties.
        local_probabilities = multimodal_report.genre_probabilities or {}
        all_genres = set(local_probabilities) | set(upstream_mixture) | {upstream_primary}
        blended = {
            genre: 0.70 * upstream_mixture.get(genre, 0.0)
            + 0.30 * local_probabilities.get(genre, 0.0)
            for genre in all_genres
        }
        if not upstream_mixture:
            blended[upstream_primary] = blended.get(upstream_primary, 0.0) + 0.35

        other_max = max(
            (score for genre, score in blended.items() if genre != upstream_primary),
            default=0.0,
        )
        blended[upstream_primary] = max(
            blended.get(upstream_primary, 0.0), other_max + 0.001
        )
        total = sum(blended.values()) or 1.0
        probabilities = {
            genre: round(score / total, 4)
            for genre, score in sorted(
                blended.items(), key=lambda item: item[1], reverse=True
            )
        }

        metadata_confirms = upstream_primary in metadata_genres
        upstream_probability = upstream_mixture.get(upstream_primary, 0.0)
        confidence = max(
            upstream_probability,
            0.75 if metadata_confirms else 0.0,
        )
        secondaries: list[str] = []
        for genre in [upstream_secondary, *metadata_genres, *probabilities.keys()]:
            if genre and genre != upstream_primary and genre not in secondaries:
                secondaries.append(genre)
            if len(secondaries) >= 2:
                break

        return GenreReport(
            trailer_mixture=probabilities,
            genre_curve=multimodal_report.genre_curve,
            dominant_genre=upstream_primary,
            secondary_genre=secondaries[0] if secondaries else None,
            secondary_genres=secondaries,
            genre_confidence=round(max(0.0, min(1.0, confidence)), 4),
            genre_probabilities=probabilities,
            genre_source=(
                "upstream-analysis+metadata"
                if metadata_confirms
                else "upstream-analysis-prior"
            ),
        )

    if metadata_genres:
        # Human-curated metadata constrains the local classifier when no
        # complete-trailer genre decision is available.
        primary = max(
            metadata_genres,
            key=lambda genre: multimodal_report.genre_probabilities.get(genre, 0.0),
        )
        secondaries = [genre for genre in metadata_genres if genre != primary][:2]
        multimodal_report.dominant_genre = primary
        multimodal_report.secondary_genre = secondaries[0] if secondaries else None
        multimodal_report.secondary_genres = secondaries
        multimodal_report.genre_confidence = max(multimodal_report.genre_confidence, 0.60)
        multimodal_report.genre_source = "metadata-constrained-multimodal"
        return multimodal_report

    if multimodal_report.dominant_genre and multimodal_report.dominant_genre != "Unknown":
        multimodal_report.genre_source = "multimodal-feature-classifier"
        return multimodal_report

    genre, confidence, distribution = genre_from_scene_types(scene_rows)
    if genre != "Unknown":
        ranked = sorted(distribution.items(), key=lambda kv: kv[1], reverse=True)
        secondary = [g for g, _ in ranked if g != genre][:2]
        return GenreReport(
            trailer_mixture=distribution,
            genre_curve=[],
            dominant_genre=genre,
            secondary_genre=secondary[0] if secondary else None,
            secondary_genres=secondary,
            genre_confidence=confidence,
            genre_probabilities=distribution,
            genre_source="scene-type-majority",
        )

    return multimodal_report



# Where analysis output folders live. The mirror inside this project is
# preferred; the upstream analyser's own folder is the fallback for a trailer
# that was just uploaded there and has not been mirrored yet. Both are read
# only -- nothing here writes to the upstream project. Derived from the repo
# layout rather than an absolute path so it survives being moved.
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent


def _output_roots() -> tuple[Path, ...]:
    configured = get_settings().emotion_output_dir.strip()
    roots = [
        _REPO_ROOT / "storage" / "outputs",
        _REPO_ROOT.parent / "Movie_Trailer-main" / "storage" / "outputs",
    ]
    if configured:
        roots.insert(0, Path(configured))
    return tuple(dict.fromkeys(path.resolve() for path in roots))


def _slugify(text: str) -> str:
    """Loose slug for comparing a trailer title to a folder name."""
    return re.sub(r"[^a-z0-9]+", "", str(text).lower())


def _resolve_output_dir(payload: RecommendationRequest) -> str | None:
    """Find this trailer's analysis folder when the caller didn't name one.

    The /latest and /prediction routes build their payload from the emotion
    API and have no filesystem path to pass, so without this the frame-level
    checks (logo placement, title card, release date) and every colour
    measurement would silently do nothing for exactly the requests the
    frontend makes.

    Matching follows the upstream analyser's own rules (see
    Movie_Trailer-main/app/api/prediction.py): exact folder name first, then
    the short hash suffix, then a slugified title comparison. Returns None
    when nothing matches, which leaves the previous behaviour intact.
    """
    if payload.trailer_output_dir:
        return payload.trailer_output_dir

    pid = (payload.source_prediction_id or "").strip()
    title = (payload.trailer_title or "").strip()
    # Trailer titles arrive as filenames from the emotion API; drop the
    # extension so "Suicide Squad ... [HD].mp4" can match its folder.
    title_slug = _slugify(Path(title).stem) if title else ""
    short_id = pid.rsplit("_", 1)[-1] if "_" in pid else pid

    for root in _output_roots():
        if not root.is_dir():
            continue
        if pid and (root / pid).is_dir():
            return str(root / pid)
        try:
            dirs = [d for d in root.iterdir() if d.is_dir()]
        except OSError:
            continue
        if short_id and len(short_id) >= 6:
            for d in dirs:
                if short_id in d.name:
                    return str(d)
        if title_slug and len(title_slug) >= 6:
            for d in dirs:
                folder_slug = _slugify(d.name)
                if title_slug in folder_slug or folder_slug.startswith(title_slug):
                    return str(d)

    logger.info("No analysis output folder found for '%s' (id=%r) — frame-level "
                "and colour checks will be skipped.", title or "<untitled>", pid)
    return None


def _load_colour_series(
    output_dir: str | None, frames_dir: Path | None, scene_rows: list[dict[str, Any]]
) -> dict[str, list[float]] | None:
    """Colour measurements for this trailer, or None if unavailable.

    Two sources, cheapest first: the colour_features.csv written by the
    offline extraction script, or a live measurement of the saved frames.
    Returning None (rather than zeros) matters -- zeros would read as a
    pitch-black trailer and generate confident, fictional colour findings.
    """
    from app.services.colour_features import COLOUR_DIMS, scene_colour_series

    if output_dir:
        csv_path = Path(output_dir) / "colour_features.csv"
        if csv_path.exists():
            try:
                cdf = pd.read_csv(csv_path)
                if len(cdf) == len(scene_rows) and all(d in cdf.columns for d in COLOUR_DIMS):
                    return {d: cdf[d].tolist() for d in COLOUR_DIMS}
            except Exception as exc:
                logger.warning("Could not read %s: %s", csv_path, exc)

    if frames_dir is not None and frames_dir.exists():
        try:
            ids = [int(r.get("scene", i + 1)) for i, r in enumerate(scene_rows)]
            return scene_colour_series(frames_dir, ids)
        except Exception as exc:
            logger.warning("Live colour measurement failed: %s", exc)

    return None


def generate_recommendations(
    payload: RecommendationRequest,
    sentiment_context: SentimentContext | None = None,
) -> RecommendationResponse:
    """End-to-end multi-modal recommendation generation pipeline.

    Enhanced to use:
    - Statistical trailer baseline (anomaly detection)
    - Data-driven genre classification (no title keywords)
    - Energy-based structure analysis
    - Evidence-based problem detection
    """
    # STEP 0 — normalise the incoming data.
    # The analysis service names columns inconsistently across its three CSVs
    # (EI vs ei, A vs audio_energy). _build_scene_rows flattens all of that
    # into one clean list of scenes so nothing downstream has to care.
    scene_rows = _build_scene_rows(payload)
    refinement_stats = _refine_scene_types(scene_rows)
    if refinement_stats["corrected"] or refinement_stats["unreliable"]:
        logger.info(
            "Scene-type refinement: corrected=%d, marked_unreliable=%d",
            refinement_stats["corrected"],
            refinement_stats["unreliable"],
        )
    trailer_title = payload.trailer_title or "Uploaded Trailer"
    popularity_context = payload.popularity_context

    total_scenes = len(scene_rows)
    total_duration = sum(r["evidence"].shot_duration for r in scene_rows) if scene_rows else 120.0

    # STEP 1 — is this a short teaser or a full theatrical trailer?
    # Judged from length and shot count. It matters because a 30-second teaser
    # and a 2.5-minute trailer have completely different expected structures.
    trailer_type = detect_trailer_type(total_duration, total_scenes)

    # STEP 2 — work out the genre. THIS MUST HAPPEN BEFORE ANY JUDGEMENT.
    # Everything after this point interprets the evidence differently
    # depending on the genre, so getting it wrong poisons every later stage.
    # Three methods are tried in order of trustworthiness — see _classify_genre.
    # Fetch metadata once. It can confirm a genre decision and is reused by
    # the later OCR/title-card checks.
    metadata = fetch_movie_metadata(trailer_title) if trailer_title else None
    genre_report = _classify_genre(
        scene_rows,
        trailer_title,
        total_duration,
        insights=payload.insights,
        metadata=metadata,
    )
    dominant_genre = genre_report.dominant_genre
    secondary_genre = genre_report.secondary_genre

    # STEP 3 — measure this trailer against itself.
    # Averages and spreads for its own scenes, used by the odd-one-out detector.
    baseline = build_trailer_baseline(scene_rows)

    # STEP 4 — bundle the genre result, including how confident we are and
    # which of the three methods produced it (reported honestly in the response).
    genre_profile = TrailerProfile(
        primary_genre=dominant_genre,
        secondary_genres=genre_report.secondary_genres,
        genre_probabilities=genre_report.genre_probabilities,
        genre_confidence=genre_report.genre_confidence,
        genre_source=genre_report.genre_source,
    )

    # STEP 5 — split the trailer into its structural acts.
    # Finds the opening, build-up, climax and ending by following the energy
    # curve, rather than assuming fixed percentages of the running time.
    structure_report = infer_beats(scene_rows, trailer_type)

    # STEP 6 — how much of the trailer is action vs dialogue vs emotion,
    # weighted by how confident the scene classifier was about each label.
    ratio_analysis = analyze_ratios(scene_rows, dominant_genre)

    # STEP 8 — Frame-level checks need the real title/release-date (ground truth,
    #    already fetched — cached, so this costs nothing extra) and the path
    #    to this trailer's scene thumbnails, if it has any.
    real_title = (metadata or {}).get("title", "") or ""
    real_release_date = (metadata or {}).get("released", "") or ""
    #    The /latest and /prediction routes cannot supply that path, so fall
    #    back to locating the folder from the trailer's identity.
    output_dir = _resolve_output_dir(payload)
    frames_dir = Path(output_dir) / "frames" if output_dir else None

    # Colour grading, needed to compare against the genre norm. Prefer the
    # precomputed CSV (offline runs), else measure the frames now (live
    # uploads). Without either, the norm check runs on structure alone and
    # says so, rather than treating "unmeasured" as "black".
    colour_series = _load_colour_series(output_dir, frames_dir, scene_rows)

    # STEP 9 — the actual decision stage.
    # Everything above was measurement; this is where the system decides which
    # scenes are genuinely problems and writes the fix for each one.
    recommendations, timeline_insights, timing_roadmap, component_scores = generate_cinematic_recommendations(
        scene_rows=scene_rows,
        trailer_title=trailer_title,
        dominant_genre=dominant_genre,
        secondary_genre=secondary_genre,
        trailer_type=trailer_type,
        structure_report=structure_report,
        baseline=baseline,
        genre_profile=genre_profile,
        popularity_context=popularity_context,
        sentiment_context=sentiment_context,
        frames_dir=frames_dir,
        real_title=real_title,
        real_release_date=real_release_date,
        colour_series=colour_series,
    )

    # ── Build response ───────────────────────────────────────────────

    avg_ei = sum(r["evidence"].ei for r in scene_rows) / total_scenes if scene_rows else 0.75

    # ==============================================================================
    # STEP 4: OVERALL PRIORITY INDEX & PRIMARY FOCUS AREA AGGREGATION
    # Aggregates scene recommendations to compute:
    # 1. Primary Focus Area (most frequent problem dimension)
    # 2. Overall Priority Index (average priority score across all scene recommendations)
    # ==============================================================================
    if recommendations:
        # Tally the focus areas to find the most frequent issue
        focus_counts: dict[str, int] = {}
        for r in recommendations:
            focus_counts[r.focus_area] = focus_counts.get(r.focus_area, 0) + 1
        main_problem = max(focus_counts, key=focus_counts.get)
        
        # Calculate the Overall Priority Index (Average of all scene priority scores)
        avg_prio = int(round(sum(r.priority_score for r in recommendations) / len(recommendations)))

        weakest_scene = max(recommendations, key=lambda r: r.priority_score, default=None)
        strongest_scene = min(recommendations, key=lambda r: r.priority_score, default=None)
    else:
        main_problem = "No significant issues detected"
        avg_prio = 30  # Low priority default (Clean trailer ready for release)
        weakest_scene = None
        strongest_scene = None

    # Build overall recommendation text
    genre_str = f"{dominant_genre}"
    if genre_report.secondary_genres:
        genre_str += f" / {', '.join(genre_report.secondary_genres[:2])}"
    # Describes how the genre was actually decided. The old version tested for
    # "lmtd-real-ml", a source that no longer exists, so every trailer was
    # labelled a rule-based estimate even when the CLIP scene-type classifier
    # had decided it.
    genre_source_note = {
        "scene-type-majority": "majority of CLIP-labelled scene types",
        "rule-based-fallback": "rule-based estimate — no usable scene labels",
    }.get(genre_report.genre_source, genre_report.genre_source or "unknown source")

    num_recs = len(recommendations)
    if num_recs == 0:
        overall_rec = (
            f"Trailer classified as {genre_str} ({genre_source_note}; confidence: {genre_report.genre_confidence:.0%}). "
            f"No significant structural or pacing problems detected. "
            f"The trailer's rhythm and escalation appear well-balanced for the {dominant_genre} genre."
        )
    else:
        severity_counts = {"HIGH": 0, "MEDIUM": 0, "LOW": 0}
        for r in recommendations:
            severity_counts[r.severity] = severity_counts.get(r.severity, 0) + 1

        issue_summary = ", ".join(
            f"{count} {sev.lower()}-severity" for sev, count in severity_counts.items() if count > 0
        )
        overall_rec = (
            f"Trailer classified as {genre_str} ({genre_source_note}; confidence: {genre_report.genre_confidence:.0%}). "
            f"Found {num_recs} actionable issue(s): {issue_summary}. "
            f"Primary focus area: {main_problem}."
        )

    summary = RecommendationSummary(
        trailer_title=trailer_title,
        total_scenes=total_scenes,
        average_emotional_intensity=round(avg_ei, 2),
        weakest_timeframe=weakest_scene.timeframe if weakest_scene else None,
        strongest_timeframe=strongest_scene.timeframe if strongest_scene else None,
        main_problem=main_problem,
        overall_recommendation=overall_rec,
        overall_reaction="High" if avg_ei >= 0.65 else "Moderate" if avg_ei >= 0.40 else "Low",
        popularity_reaction=popularity_context.predicted_reaction if popularity_context else "Positive",
        popularity_score=popularity_context.popularity_score if popularity_context else 0.75,
        engagement_rate=popularity_context.engagement_rate if popularity_context else 0.045,
        recommendation_model=MODEL_NAME,
        recommendation_model_version=MODEL_VERSION_DEFAULT,
        mean_prediction_confidence=round(
            sum(r.confidence for r in recommendations) / len(recommendations), 4
        ) if recommendations else 1.0,
    )

    rec_id = f"REC-{uuid.uuid4().hex[:8].upper()}"
    now_iso = datetime.now(timezone.utc).isoformat()

    return RecommendationResponse(
        summary=summary,
        timeline_insights=timeline_insights,
        recommendations=recommendations,
        popularity_context=popularity_context,
        sentiment_context=sentiment_context,
        model_metrics=_load_model_metrics(),
        source="evidence-based-engine",
        source_prediction_id=payload.source_prediction_id or payload.trailer_id,
        recommendation_id=rec_id,
        created_at=now_iso,
        id=rec_id,
        trailerTitle=trailer_title,
        sourceUrl="",
        generatedAt=now_iso,
        overallPriorityScore=avg_prio,
        modelConfidence=int(genre_report.genre_confidence * 100),
        focusArea=main_problem,
        targetAudienceReach=int(min(96, max(70, 75 + avg_ei * 20))),
        componentScores=component_scores,
        timings=timing_roadmap,
        trailer_profile=genre_profile,
        trailer_baseline=baseline,
        structural_phases=structure_report.phases,
    )
